services:
  - type: web
    name: mepf-server
    runtime: python
    plan: free

    buildCommand: pip install -r requirements.txt

    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT

    envVars:
      - key: MEPF_SERVER_URL
        value: https://mepf-server.onrender.com

      - key: MEPF_API_KEY
        sync: false

      - key: PYTHONUNBUFFERED
        value: "1"
